version: '3'
services:
  scraper:
    image: ubuntu   
    container_name: scraper   
    volumes:
    - "./playlist:${FOLDERSHARED}"
    - ./code/:/code
    environment:
      DOMAIN: ${DOMAIN}
      MASK: ${MASK}
      FOLDERSHARED: ${FOLDERSHARED}
      HOSTIP: ${HOSTIP}
      PROXY: ${PROXY}
      PORTPROXY: ${PORTPROXY}
      IGNOREPASTEVENTS: ${IGNOREPASTEVENTS}
      PASTEVENTSTHRESOLDHOURS: ${PASTEVENTSTHRESOLDHOURS}
    entrypoint:
      - /code/entrypoint.sh
  aceproxy:
    image: ikatson/aceproxy
    container_name: aceproxy
    ports:
      - "${PORTPROXY}:8000" 
    volumes:
      - "./code/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf" 
  webacestream:
    build: .   
    container_name: webacestream 
    volumes:
    - "./html:/var/www/html"
    - "./playlist/:/playlist"
    ports:
      - "${WEBPORT:-8181}:80"